language: python
python:
- '2.7'
- '3.5'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: iandees
  password:
    secure: iUhnVoz+l0msDdJbAXDNUSUbHWJkmxvkdxY4XFHBE5wZZ6cJ8WMdIk09vOT4JXmkllV0RKflvC/o+9WG5Bu8dzEsVR6mch6zV+kIsBAiMBpXUK34f/TPiHFg41t508CH9MDWAq3I3Arkw2IVcyrqWONsI7MxU/oDkBmC2M2ze5s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: openaddresses/pyesridump
